CREATE DATABASE T_DPS

USE T_DPS

CREATE TABLE Salarios
(
	IdSalario INT PRIMARY KEY IDENTITY
	,Valor MONEY
);

CREATE TABLE Habilidades
(
	IdHabilidade INT PRIMARY KEY IDENTITY
	,Nome VARCHAR (250) NOT NULL
):

CREATE TABLE Departamentos
(
	IdDepartamento INT PRIMARY KEY IDENTITY
	,Nome VARCHAR (210) NOT NULL UNIQUE
);

CREATE TABLE Funcionarios
(
	IdFuncionarios INT PRIMARY KEY IDENTITY
	,Nome VARCHAR (200) NOT NULL UNIQUE
	,IdSalario INT FOREIGN KEY REFERENCES
	,IdHabilidade INT FOREIGN KEY REFERENCES
	,IdDepartamento INT FOREIGN KEY REFERENCES
);